trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration Release
  displayName: 'dotnet build'

- script: dotnet test --no-build --verbosity normal
  displayName: 'dotnet test'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

